import importlib
import pathlib
import sys
import streamlit as st

# -----------------------------------------------------------------------------
# Streamlit global configuration
# -----------------------------------------------------------------------------

st.set_page_config(
    page_title="Crypto Strategy Engine",
    page_icon="🚀",
    layout="wide",
)

# -----------------------------------------------------------------------------
# Utility: dynamic multipage handler (works both locally and on Streamlit Cloud)
# -----------------------------------------------------------------------------

ROOT_DIR = pathlib.Path(__file__).parent
PAGES_DIR = ROOT_DIR / "pages"

# ensure repo root and pages/ are importable
sys.path.append(str(ROOT_DIR))
sys.path.append(str(PAGES_DIR))


# Map human‑readable names to module import paths
PAGES = {
    "Home": "home_page",  # optional simple homepage

    # pages/ directory (auto‑generated by Streamlit multipage convention)
    "Data Management": "pages.1_Data_Management",
    "Strategies": "pages.2_Strategie",

    # new Data Console (root level, created via canvas)
    "Data Console": "3_Data_Console",  # import at repo root
}

# -----------------------------------------------------------------------------
# Sidebar navigation
# -----------------------------------------------------------------------------

st.sidebar.title("Navigation")
selection = st.sidebar.radio("Go to", list(PAGES.keys()))

# -----------------------------------------------------------------------------
# Lazy import and run selected page
# -----------------------------------------------------------------------------

module_path = PAGES[selection]

if module_path == "home_page":
    st.markdown("""
        # Crypto Strategy Engine
        Benvenuto! Usa la barra laterale per navigare tra:
        - **Data Management** (fetch, quality, upload CSV)
        - **Strategies** (backtest price‑based)
        - **Data Console** (setup e monitoraggio fonti on‑chain, deriv, social)
    """)
else:
    try:
        module = importlib.import_module(module_path)
        # If the module defines a `main()` function, call it to avoid rerun on import
        if hasattr(module, "main"):
            module.main()
    except ModuleNotFoundError as e:
        st.error(f"❌ Impossibile caricare il modulo '{module_path}'. Assicurati che il file esista e sia nel PATH.\n{e}")
